// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'FirebaseAPIKey',
    appId: '1:1082103912629:web:1809d2f6a46196c6dfc6fc',
    messagingSenderId: '1082103912629',
    projectId: 'flutter-chat-app-37b55',
    authDomain: 'flutter-chat-app-37b55.firebaseapp.com',
    storageBucket: 'flutter-chat-app-37b55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FireBaseAPIKey',
    appId: '1:1082103912629:android:24b65c356eb7ff63dfc6fc',
    messagingSenderId: '1082103912629',
    projectId: 'flutter-chat-app-37b55',
    storageBucket: 'flutter-chat-app-37b55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'FireBaseAPIKey',
    appId: '1:1082103912629:ios:87570264b56be35fdfc6fc',
    messagingSenderId: '1082103912629',
    projectId: 'flutter-chat-app-37b55',
    storageBucket: 'flutter-chat-app-37b55.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_jWdol75T-NUtgBzLE4uq-Xe599DXGok',
    appId: '1:1082103912629:ios:87570264b56be35fdfc6fc',
    messagingSenderId: '1082103912629',
    projectId: 'flutter-chat-app-37b55',
    storageBucket: 'flutter-chat-app-37b55.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpYQfIwzqdWpvtPWDlX6UIZyRkPItKNpQ',
    appId: '1:1082103912629:web:2225d6a1bf18dd30dfc6fc',
    messagingSenderId: '1082103912629',
    projectId: 'flutter-chat-app-37b55',
    authDomain: 'flutter-chat-app-37b55.firebaseapp.com',
    storageBucket: 'flutter-chat-app-37b55.firebasestorage.app',
  );
}
